[package]
name = "metal"
version = "0.0.1"
authors = ["Felix Kaaman <trundmatu@gmail.com>"]
readme = "README.md"
keywords = ["metal", "graphics", "bindings"]
license = "MIT OR Apache-2.0"

[dependencies]
cocoa = "0.2.5"
bitflags = "0.4.0"
libc = "0.2"
objc = "0.1.8"
objc-foundation = "0.0.4"
objc_id = "0.0.2"
block = "0.1.4"

[dev-dependencies]
winit = "0.4.9"

[[example]]
name = "window"
path = "examples/window/main.rs"

[[example]]
name = "caps"
path = "examples/caps/main.rs"
